version: 2
jobs:
  two:
    docker: 
      - image: 'cimg/python:3.6'
      - image: circleci/postgres:9.6-alpine
  
    steps:
      - checkout
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install pip 
           command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install awscli 
           command: sudo pip install awscli
      - run : aws redshift --region us-west-2 describe-clusters
      - run : sudo apt-get update  
      - run : sudo apt-get install -y postgresql-client
      - run: whoami
      - run : 
          name: psql command
          command: |
            export PGPASSWORD=$PGPASSWORD
            psql -h 'my-redshift-instance.cprffuyieidy.us-west-2.redshift.amazonaws.com' -p 5439 -U epanjwani -d testdb << EOF
            create table public.circlecitest(catid smallint not null distkey sortkey,catgroup varchar(10),catname varchar(10),catdesc varchar(50));
            copy public.circlecitest from 's3://redshifttestbucket/category_object_paths.json' credentials 'aws_iam_role=arn:aws:iam::181935492667:role/MyTestRedshiftRole' json 's3://redshifttestbucket/category_jsonpath.json';
            select * from public.circlecitest;
            EOF
      
            
workflows:
  version: 2
  one_and_two:
    jobs:
      - two
