version: 2
jobs:
  two:
    docker: 
      - image: 'cimg/python:3.6'
      - image: circleci/postgres:9.6-alpine
  
    steps:
      - checkout
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install pip 
           command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install awscli 
           command: sudo pip install awscli
      - run : aws redshift --region us-west-2 describe-clusters
      - run : sudo apt-get update  
      - run : sudo apt-get install -y postgresql-client
      - run: whoami
      - run : 
          name: psql command
          command: |
            export PGPASSWORD=$PGPASSWORD
            psql -h 'my-redshift-instance.cprffuyieidy.us-west-2.redshift.amazonaws.com' -p 5439 -U epanjwani -d testdb << EOF
            select * from public.circlecitest;
            EOF
      
            
workflows:
  version: 2
  one_and_two:
    jobs:
      - two
