version: 2
jobs:
  one:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output      
  two:
    docker: 
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          overwrite: true
          to: 's3://redshifttestbucket/'
          
          
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
