version: 2

orbs:
   aws-s3: circleci/aws-s3@x.y.z # use the AWS S3 orb in your config

workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-deploy: # Make a workflow to build and deploy your project
     jobs:
       - build
       - deploy:
           requires:
             - build # Only run deploy job once the build job has completed
             
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
       
deploy:
     docker: # Use the Docker executor for the deploy job
       - image: 'cimg/python:3.6'
   steps:
       - checkout
       - aws-s3/copy:
          arguments: '--dry-run'
          from: bucket/build_asset.txt
          to: 's3://redshifttestbucket/'
  
  
