version: 2
jobs:

  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output.txt
     
  two:
    docker: 
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install pip 
           command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install awscli 
           command: sudo pip install awscli
     
          
          
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
