version: 2
jobs:
  two:
    docker: 
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install pip 
           command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
      - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install awscli 
           command: sudo pip install awscli
          
          
workflows:
  version: 2
  one_and_two:
    jobs:
      - two
